#!/bin/sh

echo "*********************************************************************"
echo "build Speedport_NEO.img"
cd ./build/F1/
fakeroot make

echo "*********************************************************************"
echo "copy Speedport_NEO.img to Result"
cp ../../build/F1/product/F1/image/090128*.*.img ../../Result/

echo "*********************************************************************"
#make clean
echo "***************************build end*********************************"
