#!/bin/bash
# Script to install fonap on a qemu debian image and run it
# 2011 pablo@fon.com
DEBIAN_MIRROR=http://ftp.es.debian.org
NETBOOT_DIR=debian/dists/squeeze/main/installer-i386/current/images/netboot/debian-installer/i386/
QEMU_PARAMETERS="-nographic -m 128"

SRCDIR="$(dirname $(pwd)/$0)/.."
cd $SRCDIR
SRCDIR=$(pwd)
cd $SRCDIR/test
SOURCED=0
if [ $0 = "bash" ]; then
	SOURCED=1
elif [ $# -lt 1 ]; then
	echo "fonap test script"
	echo "Usage:"
	echo " fonaptest [build|server|client|bridge]"
	echo 
	echo "build:  creates debian-qemu-image.img, server.img and client.img"
	echo "        in $(pwd)/"
        echo "server: run server.img. ssh through tap0 at 192.168.50.1"
	echo "client: run client.img. ssh through tap3 at 192.168.51.1"
	echo "bridge: setup a bridge between tap1 and tap2 so client can"
	echo "        get internet connectivity and get captured through"
	echo "        the running server image"
	echo
	exit 0
fi

rootest() {
	if [ "$(id -u)" -ne "0" ]; then
		echo "You must be root, su or sudo before call. Bailing out."
		exit 1
	fi
}

build_image() {
	if [ -f debian-qemu-image.img ]; then
		echo 
		echo " An image in was already found in"
		echo " $(pwd)/debian-qemu-image.img"
		echo " Proceed executing buildserver or buildclient"
		echo " or delete it you want to rebuild"
		echo
		return 0
	fi
	if [ ! -f linux ]; then
		wget -O $SRCDIR/test/linux $DEBIAN_MIRROR/$NETBOOT_DIR/linux
	fi
	if [ ! -f initrd.gz ]; then
		wget -O initrd.gz $DEBIAN_MIRROR/$NETBOOT_DIR/initrd.gz
		mkdir /tmp/initrd
		cd /tmp/initrd
		gunzip -c $SRCDIR/test/initrd.gz | cpio -id
		create_preseed_file || exit 1 
		cp /tmp/preseed.cfg .
		rm $SRCDIR/test/initrd.gz
		find . | cpio --create --format='newc' | gzip > $SRCDIR/test/initrd.gz
		rm -fR /tmp/initrd
		cd $SRCDIR/test
	fi
	qemu -h >/dev/null 2>&1 || (echo "Qemu not found. Aborting..."; exit 1)
	qemu-img create -f qcow debian-qemu-image.img 1GB
	qemu $QEMU_PARAMETERS -kernel linux -initrd initrd.gz -hda debian-qemu-image.img -append 'console=ttyS0'
	if [ $? -ne 0 ]; then
		echo Error calling qemu
		rm debian-qemu-image.img
		exit 1;
	fi
}
setup_server() {
	if [ ! -f debian-qemu-image.img ]; then
		echo " debian-qemu-image.img not found"
		echo " create it first running fonaptest build"
		echo
		return 1
	fi
	cp debian-qemu-image.img server.img
	return 0
}
setup_client() {
	if [ ! -f debian-qemu-image.img ]; then
		echo
		echo " debian-qemu-image.img not found"
		echo " create it first running fonaptest build"
		echo
	fi
	cp debian-qemu-image.img client.img
	return 0
}

# Create tap0 used to communicate through ssh, and tap1
# used to bridge with the client
run_client() {
	if [ ! -f client.img ]; then
		setup_client || return 1
	fi
	qemu $QEMU_PARAMETERS \
-net nic,macaddr=10:10:10:10:11:02,vlan=0 -net tap,vlan=0,script=no,downscript=no \
-net nic,macaddr=10:10:10:10:11:03,vlan=1 -net tap,vlan=1,script=no,downscript=no \
-hda client.img
}
run_server() {
	if [ ! -f server.img ]; then
		setup_server || return 1
	fi
	qemu $QEMU_PARAMETERS -net user,vlan=0 -net nic,macaddr=10:10:10:10:10:01,vlan=0 \
-net nic,macaddr=10:10:10:10:10:02,vlan=1 -net tap,vlan=1,script=no,downscript=no \
-net nic,macaddr=10:10:10:10:10:03,vlan=2 -net tap,vlan=2,script=no,downscript=no \
-hda server.img
}

setup_bridge() {
	brctl addbr br0
	ifconfig tap1 0.0.0.0
	ifconfig tap2 0.0.0.0
	brctl addif br0 tap1
	brctl addif br0 tap2
	ifconfig tap1 up
	ifconfig tap2 up
	ifconfig br0 up
	ifconfig tap0 192.168.50.2
	ifconfig tap3 192.168.51.2
}

# Create preseed file using a shell HEREDOC
# to keep it inside this script
create_preseed_file () {

cat <<ENDOFFILE > /tmp/preseed.cfg
# preseed file for debian squeeze fonap testing image (x86)
d-i debconf/priority select critical
d-i debian-installer/locale string en_US
d-i console-keymaps-at/keymap select es
d-i netcfg/choose_interface select auto
# To pick a particular interface instead:
#d-i netcfg/choose_interface select eth1
d-i netcfg/dhcp_timeout string 60
d-i netcfg/get_hostname string test-server
d-i netcfg/get_domain string unassigned-domain
d-i netcfg/wireless_wep string
d-i mirror/protocol string http
d-i mirror/ftp/hostname string ftp.es.debian.org
d-i mirror/ftp/directory string /debian
d-i mirror/ftp/proxy string
d-i time/zone string Europe/Madrid
d-i clock-setup/ntp boolean true
d-i clock-setup/utc boolean true
d-i partman-auto/method string regular
#d-i partman-lvm/device_remove_lvm boolean true
#d-i partman-md/device_remove_md boolean true
#d-i partman-lvm/confirm boolean true
d-i partman/default_filesystem string ext2
d-i partman-auto/choose_recipe select atomic
d-i partman-partitioning/confirm_write_new_label boolean true
partman-partitioning partman-partitioning/unknown_label boolean true
partman-partitioning partman-partitioning/confirm_new_label boolean true
partman-partitioning partman-partitioning/confirm_write_new_label boolean true
d-i partman/choose_partition select finish
d-i partman/confirm boolean true
d-i partman/confirm seen true
d-i partman/confirm_nooverwrite boolean true
# DEFAULT PACKAGES
d-i pkgsel/include string ssh-server screen elinks lynx sudo
# grip-config hal screen uswsup splashy splashy-themes
#d-i pkgsel/upgrade select full-upgrade
popularity-contest popularity-contest/participate boolean false
# Choices: Dialog, Readline, Gnome, Kde, Editor, Noninteractive
debconf debconf/frontend select Readline
# Skip creation of root account
d-i passwd/root-login boolean false
# Normal (and sudoable) user account
d-i passwd/user-fullname string Debian User
d-i passwd/username string user
d-i passwd/user-password password password
d-i passwd/user-password-again password password
d-i passwd/user-default-groups string audio cdrom video sudo
d-i apt-setup/non-free boolean true
d-i apt-setup/contrib boolean true
d-i apt-setup/services-select multiselect security, volatile
d-i apt-setup/security_host string security.debian.org
d-i apt-setup/volatile_host string volatile.debian.org
d-i pkgsel/include string openssh-server build-essential
#d-i pkgsel/upgrade select none
d-i grub-installer/only_debian boolean true
d-i finish-install/keep-consoles boolean false
d-i finish-install/reboot_in_progress note
d-i debian-installer/exit/poweroff boolean true
console-common  console-data/keymap/policy      select  Don't touch keymap
console-common  console-data/keymap/family      select  qwerty
d-i console-keymaps-at/keymap select es
console-common  console-data/keymap/template/variant select es
d-i preseed/late_command string apt-install openssh-server; in-target echo bartolo > /root/bartolo
 # ; in-target chsh -s /bin/zsh
ENDOFFILE
return 0
}
if [ $SOURCED -eq 0 ]; then
	rootest
	case "$1" in
		build)
			build_image
			exit $?
			;;
		server)
			run_server
			exit $?
			;;
		client)
			run_client
			exit $?
			;;
		bridge)
			setup_bridge
			exit $?
			;;
		*)
			echo $1 ?
			;;
	esac
fi

